repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3
      args: ["--line-length", "84"]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
      language_version: python3.8
      name: isort (python)
      args: ["--profile", "black", "--line-length", "84"]
-   repo: https://github.com/pycqa/flake8.git
    rev: 5.0.4
    hooks:
    - id: flake8
      additional_dependencies:
        - flake8-black>=0.1.1
      language_version: python3
      args: [
        "--ignore", "C901,E203,E741,W503,BLK100",
        "--max-line-length", "84",
        "--max-complexity", "18",
        "--select", "B,C,E,F,W,T4,B9",
        "--per-file-ignores", "__init__.py:F401",
      ]
      exclude: examples
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
    - id: pydocstyle
      args: ["--ignore", "D100,D104,D105,D107,D203,D212"]
      exclude: examples
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-ast
    - id: check-added-large-files
    - id: check-merge-conflict